source "http://rubygems.org"
ruby "2.2.2"

gem "rails", '4.2.3'
gem "aws-sdk", '< 2.0'
gem 'httparty'
gem "bcrypt-ruby", "~> 3.1.2"
gem "omniauth-facebook", "2.0.1"
gem 'omniauth-twitter'
gem "koala", "2.2.0"
gem "pg", "0.18.2"
gem 'instagram'
gem "devise", "3.4.1"
gem "activerecord-session_store", "~> 0.1"
gem "jquery-rails", "3.0.4"
gem "angularjs-rails", "1.3.10"
gem "angular_rails_csrf"
gem 'angular-rails-templates'
gem "uglifier", "~> 2.1.1"
gem "font-awesome-rails", "~> 4.4.0.0"
gem "turbolinks", "2.5.3"
gem "jbuilder", "1.0.2"
gem "jquery-turbolinks", "~> 2.1"
gem "google-api-client", "~> 0.7.1", { require: "google/api_client" }
gem "omniauth-google-oauth2", "~> 0.2"
gem "rest-client", "~> 1.7"
gem "rest_in_place", "~> 2.5"
gem "activerecord-import", "0.10.0"
gem "dogstatsd-ruby", "1.6.0", { require: "statsd" }
gem "sys-uname", "~> 0.9"
gem "bootstrap-sass", "3.3.5"
gem 'sass-rails', "5.0.3"
gem 'compass-rails', "2.0.5", github: 'adwyze/compass-rails'
gem "paloma", "4.2.0"
gem 'dentaku', '~> 2.0', '>= 2.0.7'
gem "solid_assert", "~> 0.7"
gem "simple_form", "~> 3.1"
gem "valid_email", "0.0.11"
gem "logstasher", "0.6.5"
gem "nokogiri", "~> 1.6"
gem "premailer-rails", "1.8.2"
gem 'kaminari'
gem 'pusher'
gem 'versionist'
gem 'json-schema'
gem 'redis'
gem 'redis-rails'
gem 'nprogress-rails'
gem 'thread'
gem 'intercom-rails'
gem 'rack-cors', :require => 'rack/cors'
gem 'faker'
gem 'gon'
gem 'rbtrace'
gem 'heapy'
gem 'builder'

# Introducing mongoDB
gem 'mongoid', '5.1.1'
gem 'tenacity'

# Required for sidekiq and UI
gem 'sidekiq', '4.1.1'
gem 'redis-namespace'
gem 'sidekiq-history'
gem 'sidekiq-monitor-stats'

# Needed for reporting Sidekiq job failures to Sentry
gem 'sentry-raven'
gem 'sinatra', require: nil
gem 'sidekiq-failures'
gem 'facter'
gem 'sass', '3.4.7'

# Needed to copy data from prod to devel
gem 'replicate'

# profiler. Will not do any harm in prod
gem 'rack-mini-profiler', { require: false }
gem 'flamegraph'
gem 'stackprof'
gem 'puma'
gem 'puma_worker_killer'
gem 'twitter-ads'

gem 'whenever', { require: false }

# Needed for image editor
gem 'rmagick'

group :development do
  # gem "rails-footnotes", "~> 4.1"
  # gem "railroady", "~> 1.3"
  # gem "meta_request", "~> 0.3"
  gem "pry-rails", "0.3.4"
  gem "capistrano", "~> 3.4", { require: false }
  gem "capistrano-rails", "~> 1.1", { require: false }
  gem "capistrano-bundler", "~> 1.1", { require: false }
  gem "capistrano3-puma"
  gem 'capistrano-sidekiq'
  gem 'capistrano-rvm'
  gem "rubocop", "~> 0.37.2", { require: false }
  gem "overcommit", "~> 0.32"
  gem "letter_opener_web", "~> 1.3"
  gem "habtm_generator", "~> 0.3"
  gem "web-console", "~> 2.2.1"

  # better errors
  gem "better_errors"
  gem "binding_of_caller"

  # live reload for rails css/js
  gem "guard", ">= 2.2.2", { require: false }
  gem "guard-livereload", { require: false }
  gem "rack-livereload"
  gem "rb-fsevent", { require: false }
end

group :profile, :development do
  gem "ruby-prof"
end

group :development, :test do
  gem "byebug", "5.0.0"
  gem "jasmine", "2.4.0"
  gem "parallel_tests", "2.3.1"
  gem "teaspoon-jasmine"
  gem 'phantomjs'
  gem 'active_record_query_trace'

  # For Pronto

  gem 'pronto'
  gem 'pronto-rubocop'
  gem 'pronto-flay'
  gem 'pronto-reek'
  gem 'pronto-rails_best_practices'
  gem 'pronto-rails_schema'
  gem 'pronto-eslint'
end

group :test do
  gem "pusher-fake"
  gem "database_cleaner", "1.5.1"
  gem "webmock", "~> 1.21"
  gem "vcr", "~> 2.9"
  gem "connection_pool", "~> 2.1"
  gem "capybara", "~> 2.4"
  gem "capybara-webkit", "1.6"
  gem "capybara-screenshot", "~> 1.0"
  gem "simplecov", "0.10.0"
  gem "rspec-rails"
  gem 'shoulda-matchers', '~> 3.0'
  gem "factory_girl_rails", "~> 4.5"
  gem 'responders'
  gem "fakeredis"
  gem 'rspec-sidekiq'
  gem 'rspec-retry'
  gem "rspec-instafail"
  # Needed for image editor
  gem 'phashion'
end

group :production, :staging do
  gem "ar-octopus", "~> 0.8"
end

group :assets do
  gem 'coffee-rails'
end
